### ISSUE TITLE
[BE] Test @BeforeEach 메서드 네이밍을 일관성 있게 변경한다.

### ISSUE THREAD

**Issue by meatsby** [woowacourse-teams/2022-gong-check#211]
## as-is
- 현재 Test @BeforeEach 메서드 네이밍이 `init()` 혹은 `setUp()` 등으로 일관되지 않다.

## to-be
- 논의 후 일관성 있는 네이밍으로 변경한다.

**Comment by kimchan123** [comment]
동의 합니다
