### ISSUE TITLE
[ALL] URI 엔드포인트에 hostId가 추가되어야 한다.

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse-teams/2022-gong-check#23]
## as-is
- hostId가 없는 엔드포인트는 토큰의 subject와 요청하는 방의 hostId가 같은지 검증할 수 없다.

## to-be
- 인증이 필요한 URI 엔드포인트에 hostId를 추가한다.

**Comment by awesomeo184** [comment]
안해도 될지도...?

**Comment by awesomeo184** [comment]
토큰이 발행됐다는 것은 유효한 hostId라는 것을 알 수 있기 때문에, 토큰에 들어있는 hostId로 방을 조회하는 방법을 사용한다면 굳이 URI 엔드포인트를 변경하지 않아도 될 듯

**Comment by jinyoungchoi95** [comment]
인증된 host를 가지고 token을 생성하기 때문에 토큰에서 가져온 hostId를 url에 추가하여 검증할 필요가 없는 것으로 결정하여 회의 종료
