### ISSUE TITLE
[BE] host를 find할 때 memberService에서 처리를 하는 것이 더 낫지 않을까요?

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse-teams/2022-gong-check#29]
## as-is
- 현재 memberRepository에서 Optional을 반환하고, 다른 서비스에서는 orElseThrow로 중복되는 예외처리를 하고 있음.

## to-be
- 다른 서비스들이 memberService를 의존하도록하고 여기서 예외처리를 하도록 수정.

의견 남겨주세요 ♡

**Comment by cks3066** [comment]
❤️

**Comment by jinyoungchoi95** [comment]
https://github.com/eternity-oop/Woowahan-OO-02-domain-service/blob/af6a52474639ed58250d9072b4fcdb8cb3fc1ccc/src/main/java/org/eternity/food/domain/order/OrderValidator.java

**Comment by awesomeo184** [comment]
`Host getById(hostId) throws NotFoundException` 형태로 변경하기로 결정.

널 처리를 따로 해야하는 경우 메서드 네임을 find로 사용
