### ISSUE TITLE
[BE] 무엇을 로깅해야할까? 난 정말 궁금해

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse-teams/2022-gong-check#325]
무엇을 로깅해야할지, 로깅 시스템을 어떻게 구축해야할지 논의해봅시다. 로깅 시스템이 구축되면 이 이슈는 닫도록 하겠습니다.

**Comment by awesomeo184** [comment]
https://www.freecodecamp.org/news/how-to-use-logs-effectively-in-your-code/

**Comment by jinyoungchoi95** [comment]
- controlleradvice에서 잡고있는 값들
- 외부 라이브러리를 연결한 로직들

**Comment by awesomeo184** [comment]
NotFoundException을 발생시킬때, exception정보와 함께 입력된 id를 넘기고 이를 controllerAdvice에서 로깅처리를 해봐도 좋을듯!

**Comment by awesomeo184** [comment]
debug모드로 hibernate에서 생성하는 sql문 로깅

**Comment by jinyoungchoi95** [comment]
> NotFoundException을 발생시킬때, exception정보와 함께 입력된 id를 넘기고 이를 controllerAdvice에서 로깅처리를 해봐도 좋을듯!

로깅하면서 에러메시지 관련한 부분들을 구체화하도록 수정방향 잡는걸로

**Comment by awesomeo184** [comment]
로깅 전략 제의

## prod
level - info
appender - file

## dev
level - debug
appender - file

## local
level - debug
appender - stdout

**Comment by awesomeo184** [comment]
> NotFoundException을 발생시킬때, exception정보와 함께 입력된 id를 넘기고 이를 controllerAdvice에서 로깅처리를 해봐도 좋을듯!

생각해보니 이렇게하면 어떤 레포지토리에서 발생한 예외인지 알 수 없음

**Comment by jinyoungchoi95** [comment]
각각의 호출에 대한 전체 흐름을 로깅해두어야 차후 트래픽관리에서 어떤 호출이 자주 일어났는지 확인할 수 있음

**Comment by meatsby** [comment]
### 현재 로깅 기준
`Info` - 사용자가 E2E 에서 겪을 수 있는 예외 상황 + 강조하고 싶은 로직
`Warn` - Postman 또는 curl 과 같은 현재 E2E 구조 상 이루어질 수 없는 예외
`Error` - 외부 API 예외

현재 잡아놓은 기준은 위와 같습니다.
하지만, 로깅을 적용하면서 마주친 문제점들이 존재합니다.
예를 들어, `Warn` 같은 경우, 프론트에서 잡아줄 수 없는 예외에 대해 `Warn` 로그를 찍도록 기준을 잡은 상태입니다.
여기서 생각해 볼 수 있는 것이, 어? "이거 프론트에서 예외 처리 하나?" 와 같은 프론트 의존적인 로깅이 되는 것 같아, 이에 대해 논의해보고자 합니다.

만약, 서버 입장에서만 생각한 로깅이라면, 현재 `Info` 와 `Warn` 으로 구분 지은 기준을 `Info` 로 합치고, `Error` 를 `Warn` 으로 구성하는 것이 어떤지 궁금합니다.

**Comment by awesomeo184** [comment]
Discussion tab으로 이동
