### ISSUE TITLE
[BE] 테이블을 설계한다.

### ISSUE THREAD

**Issue by cndqjacndqja** [woowacourse-teams/2022-gong-check#4]
## as-is
- 테이블이 설계되지 않은 상태이다.

## to-be
- 테이블 ERD를 설계한다.

**Comment by cndqjacndqja** [comment]
현재 DB 테이블 설계도 입니다.

![image](https://user-images.githubusercontent.com/48307960/176991151-7e3fa746-701e-4c17-a0f7-50e5ba87704b.png)

**Comment by cndqjacndqja** [comment]
## 논의 사항
현재 DB Space 테이블 컬럼명(img_url)과 Entity 필드명(imageUrl)이 서로 다른 상태입니다.
이걸 맞춰줘야 해서 img처럼 축약어를 사용할지, image로 풀네임을 사용할지 논의해보면 좋을 것 같네요!

**Comment by awesomeo184** [comment]
DB에서도 축약어는 사용하지 않는 걸로!

**Comment by cndqjacndqja** [comment]
DB member 테이블명이 올바르지 않은 것 같아요.
현재 Member에는 공간을 만드는 사람이라서, 정확하게 분리하기 위해 host로 변경하는 것이 좋을 것 같네요!

(+ 그리고 추후에 Guest라는 Table이 생길 수도 있을 것 같네요)

**Comment by cndqjacndqja** [comment]
isChecked, isActive -> checked, active로 필드명이 변경되었습니다.

**Comment by meatsby** [comment]
Space 의 img_url 이 아직 변경되지 않았습니다.
Job 에 새로운 필드 slack_url 이 추가될 예정입니다.

**Comment by jinyoungchoi95** [comment]
설계는 전부 마무리되고 릴리즈된 상태이기때문에 이슈닫습니다
db 수정필요시 추가 이슈로 진행합니다
