### ISSUE TITLE
[FE] Guest 기능 URL 수정 건의

### ISSUE THREAD

**Issue by meatsby** [woowacourse-teams/2022-gong-check#415]
## as-is
1. `https://www.gongcheck.shop/enter/{쿼리치공간}/pwd` 에서 입장코드 입력
2. `쿼리치공간` 토큰 획득
3. `https://www.gongcheck.shop/enter/{오리공간}/spaces` 접근
4. `오리공간` URL 을 가지고 접근했지만 `쿼리치공간`이 보임
5. `https://www.gongcheck.shop/enter/{오리방}/pwd` 에서 입장코드 입력
6. `쿼리치공간` 토큰 제거 후 `오리공간` 토큰 획득
7. `https://www.gongcheck.shop/enter/{오리공간}/spaces` 접근
8. 정상적으로 `오리공간`이 보임

## to-be
- 누군가가 제공하는 체크리스트를 사용하려면 URL 이 필요함
- `/enter/{entranceCode}/pwd` 에서 토큰 획득
- 이후 페이지에선 entranceCode 가 필요한가?
- 차라리 `https://www.gongcheck.shop/enter/spaces` 같은 URL 로 토큰에 해당하는 체크리스트를 보여주는 것이 맞지 않는가. 토큰이 없다면 접근이 불가능할 것이고 이렇게 변경한다면 `쿼리치토큰`을 가지고 `https://www.gongcheck.shop/enter/{오리공간}/spaces` 에 접근했는데 `쿼리치공간`이 보여지는 괴리감이 없어질 수 있을 것 같다 라는 생각.

**Comment by cks3066** [comment]
entranceCode를 바탕으로 토큰을 따로 관리하는 방향으로 수정되어서, 해당 이슈는 close 하겠습니다.
