### ISSUE TITLE
[BE] 임시로 작성한 data.sql을 제거하는 방법을 논의한다.

### ISSUE THREAD

**Issue by jinyoungchoi95** [woowacourse-teams/2022-gong-check#43]
## as-is
- guest기능만 있는 현재 인수테스트 내에서 필요한 데이터를 넣기 위해 임시로 `data.sql`을 사용한 상태
- `data.sql`을 통한 데이터 삽입의 경우 어떻게 데이터가 삽입되었는지 해당 파일을 들어가서 확인해야하며, `data.sql`이 spring data initialize 실행 시 테스트 격리를 진행하지 못하는 이슈가 있다

## to-be
- `data.sql`을 사용하지 않고 초기 데이터를 삽입할 수 있는 좋은 방법에 대한 논의를 한다

**Comment by awesomeo184** [comment]
적용 완료
