### ISSUE TITLE
[FE] 메인 화면 구성을 해야한다.

### ISSUE THREAD

**Issue by intae92** [woowacourse-teams/2022-gong-check#468]
메인 화면 구성을 해야한다.

**Comment by cks3066** [comment]
기존 #123 이슈에서 다루고 있는 내용과 동일하여 해당 이슈는 close하겠습니다.

**Comment by cks3066** [comment]
#123 이슈에 해당하는 관리자 패이지의 홈과 해당 메인 페이지가 서로 다른 페이지가 되어 해당 이슈 reopen합니다
