### ISSUE TITLE
[ALL] 도메인 용어에 대한 추가적인 정의에 대해서 논의한다

### ISSUE THREAD

**Issue by jinyoungchoi95** [woowacourse-teams/2022-gong-check#47]
## as-is
- "진행 작업"이라는 단어가 와닿지 않음
- "Job(작업)"에서 "Section(구역)"을 가지고 "Task(세부작업)"을 가지는데 `세부작업의 진행작업`으로 연결되어 매끄러워보이지 않음

## to-be
- 새로운 용어에 대한 논의를 진행한다

**Comment by awesomeo184** [comment]
"진행중인 작업이 있는지 확인한다"라는 명세도 점검할 필요가 있을듯요.

`/api/jobs/{jobId}/active` 이 API를 통해서 확인하는 내용이 결국 Job과 연결되는 RunningTask가 존재하는지 확인하는 것인데, 이를 확인하는 메서드를 `isJobActivated`라고 해도될지?

그렇다면 이 기능은 JobService에 있어야할지, TaskService에 있어야할지 고민되네요

**Comment by awesomeo184** [comment]
논의 완료
