### ISSUE TITLE
[BE] API endpoint에 대한 재설계를 논의한다

### ISSUE THREAD

**Issue by jinyoungchoi95** [woowacourse-teams/2022-gong-check#48]
## as-is
- 새로운 진행 작업 생성인 `POST /api/jobs/{jobId}`가 정확한 resource를 가르키는 것에 대한 의문이 발생

## to-be
- resource를 관리한다라는 차원에서 결국 `/api/jobs/{jobId}/tasks/new`와 같은 `tasks`에서 이어나가거나 최소한 `{jobId}` 이후의 행위가 모호한 것에 대해서 논의를 진행하여야 함

**Comment by awesomeo184** [comment]
논의완료
