### ISSUE TITLE
[FE] lighthouse user flow에 맞게 성능 분석 리포트를 자동화한다.

### ISSUE THREAD

**Issue by intae92** [woowacourse-teams/2022-gong-check#494]
## 현재 상황
- 현재 특정 페이지만 성능 분석을 하고 있다. 다른 url 페이지를 성능 분석 하기 위해서는 로그인과 서버로부터 받아오는 데이터가 필요하기 때문이다.
- `puppeteer`를 활용해야 해서 lighthouse user flow에 맞게 성능 분석 리포트를 자동화한다.
- 학습이 필요하다....

## 참고
- [lighthouse user flows](https://web.dev/lighthouse-user-flows/)
- [Lighthouse의 User Flow (toast.ui)](https://ui.toast.com/weekly-pick/ko_20211202)

**Comment by cks3066** [comment]
해줭~

**Comment by intae92** [comment]
나~~~아~~~중~~~에 할꺼임...후...절레절레

**Comment by intae92** [comment]
일정상 하지 못할 꺼 같아 클로즈 합니다.
