### ISSUE TITLE
[BE] 이미지 반환 시 webp 확장자로 반환할 수 있도록 전환한다.

### ISSUE THREAD

**Issue by jinyoungchoi95** [woowacourse-teams/2022-gong-check#495]
현재 이미지 서버에서는 이미지를 저장하며, was에서 upload기능과 resize기능을 겸하고 있습니다.

또한 저장 시 원본이미지를 저장하며 허용된 확장자명은 다음과 같습니다.
- gif
- jpg
- jpeg
- png
- svg

따라서 resize하는 경우 이미지를 resize함과 동시에 원본에 저장된 이미지 파일확장자를 붙여 반환하고 있는데요. 프론트에서 lighthouse 성능 분석 결과 다음과 같은 리포트가 발생합니다.
![image](https://user-images.githubusercontent.com/69106910/184815995-9eae7abf-d90b-4e54-b9f4-fc1f6dab45c3.png)
따라서 성능 분석 결과 차세대 형식으로 변경 요청받은 `webp` 확장자로 변경하여 반환할 수 있도록 수정하여야 합니다.
(`webp`는 구글에서 발표한 이미지 포멧으로 png, jpeg 대비 20%정도의 압축 효율을 지니고 있어 해당 방법이 추천되고 있는 듯 합니다.)

다만 문제는 `webp` 파일 형식으로의 변경이 자바에서는 까다롭습니다.
`webp`로의 변경을 위해서는 C로 쓰여져있는 코덱을 고려할 수 있는데요. 이를 자바에서 직접 활용하기 위해서는 JNI로 C코드를 직접 로드하여 사용하여야 합니다. 다만 이 작업의 경우 상당히 오랜 시간이 걸리기 때문에 이걸 라이브러리의 형태로 만들어서 사용하는데 공수비용으로 인하여 고려점에서 제외하려 합니다.
`webp`로의 변경을 위해서는 C로 쓰여져있는 [코덱](https://chromium.googlesource.com/webm/libwebp) 혹은 이를 래핑하고 있는 바이너리로 제공되어있기 때문에 자바에서는 이를 직접 활용하기 위해서는 JNI로 C코드를 직접 로드하여 사용하여야합니다.
혹은 C로 쓰여있는 코덱을 래핑한 바이너리를 사용할수도 있습니다. 해당 부분도 결국 바이너리를 사용하기 위해서 라이브러리의 형태로 만들어서 사용하여야하기 때문에 공수비용으로 인하여 고려점에서 제외하였습니다.

결과적으로 이를 모두 래핑하여 제공하고 있는 [scrimage](https://sksamuel.github.io/scrimage/)를 사용함으로써 이미지 프로세싱에 대한 부담을 덜어내고자합니다. (기존에 사용하고 있는 이미지 리사이징에 대한 부분도 좀더 추상화를 진행할 수 있을 것 같네요)

차후에는 해당부분을 TF팀을 만들어서 라이브러리의 형태로 저희가 사용하는 기술에 대해서 구현체를 잡고 진행해도 좋을 것 같습니다.

---

참고자료
- https://sightstudio.tistory.com/57

**Comment by jaeyeonling** [comment]
잘 정리해주셨어요 👍 
전환하셔도 좋습니다 ㅎㅎ
