### ISSUE TITLE
[BE] allCheck 메서드에 이벤트를 발생시킨다.

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse-teams/2022-gong-check#519]
현재 allCheck 메서드에서는 클릭 이벤트를 발생시키지 않고 있어서, 비동기 처리가 되지 않고 있다. 

allCheck에도 비동기 처리가 되도록 수정한다.

**Comment by cks3066** [comment]
#456 이슈에서 해결하고 PR 보낼 예정이라 close 하겠습니다.
