### ISSUE TITLE
[FE] 랜딩 페이지 관련 코드 리팩토링

### ISSUE THREAD

**Issue by cks3066** [woowacourse-teams/2022-gong-check#536]
gongcheck.day 로 접속했을 시 보이는 랜딩 페이지의 코드가 분리되어있지 않고 작성되어있다. 
해당 코드를 기존의 코드 작성 방식과 일치하도록 리팩토링한다.

**Comment by intae92** [comment]
해당 이슈의 같은 내용의 이슈를 이미 수정해서 클로즈 합니다.

**Comment by intae92** [comment]
재수정을 해야 해서 리오픈 합니다.
