### ISSUE TITLE
[FE] 정적 리소스에 대해 캐시 정책을 적용해야 한다.

### ISSUE THREAD

**Issue by intae92** [woowacourse-teams/2022-gong-check#542]
![스크린샷 2022-09-05 오후 5 25 23](https://user-images.githubusercontent.com/56149367/188409413-c00c4d1a-254e-4ee4-9ecc-ae76b4f7d499.png)

캐시 정책을 정해야 한다.

**Comment by cks3066** [comment]
nginx에 캐시 설정하여 해당 이슈 close 하겠습니다.

HTML - max-age = 0, etag로 변동 내역 관리
JS,CSS - max-age = 1년,  etag, 임의의 파일 이름으로 변동 내역 관리
assets - max-age = 1달, etag로 변동 내역 관리
