### ISSUE TITLE
[ALL] 1.3.0 릴리즈 배포 전 QA 사항

### ISSUE THREAD

**Issue by cks3066** [woowacourse-teams/2022-gong-check#625]
이슈에 대한 상황은 코멘트로 남겨주세요.

**Comment by jinyoungchoi95** [comment]
host 로그아웃 진행 시 하단에 인증정보 만료라고 표기됨
-> 직접 로그아웃을 한것이므로 인증정보 만료가 아닌 로그아웃되었다는 메시지

**Comment by awesomeo184** [comment]
모바일에서 체크리스트 화면에 접속한 후, 다른 앱을 켜서 몇분 하다가 다시 체크리스트 화면 와서 클릭하면 안됨. 근데 새로고침하거나 창 나갔다가 들어오면 됨

**Comment by cks3066** [comment]
닉네임 수정 api가 적용되어있지 않음

**Comment by intae92** [comment]
[user 체크 리스트 lazy loading 이슈](https://github.com/woowacourse-teams/2022-gong-check/issues/624)

**Comment by awesomeo184** [comment]
![image](https://user-images.githubusercontent.com/63030569/196599348-2a7e9446-93c9-4cff-beec-fae20a53157b.png)
![image](https://user-images.githubusercontent.com/63030569/196599544-b0a5e28b-c734-4408-ad73-ec61b713e13b.png)

사용자 페이지 토큰 관련 이슈.

발생 상황.
모바일에서 ~/pwd로 들어가지 않고
~/spaces로 바로 들어가면, 토큰이 존재하지 않아서 /pwd 페이지로 가게 된다.
이때 비밀번호를 입력해도 `존재하지 않는 페이지입니다!`라는 오류 페이지가 뜹니다.
나는 썸오 데헷 뿌잉뿌잉

**Comment by jinyoungchoi95** [comment]
<img width="2559" alt="스크린샷 2022-10-19 오후 1 46 11" src="https://user-images.githubusercontent.com/69106910/196599914-b687c532-af9f-4364-862d-f8796d3a3102.png">

submission 상세 조회에서 왼쪽상단 홈을누르면 홈으로감 / 다른쪽에서는 아이콘 클릭에 대한 기능이없음

-> 왼쪽상단 아이콘버튼에 대한 동작 통일 필요해보임

**Comment by jinyoungchoi95** [comment]
공간 이름 작성 시 길이 제한이 있다라는 표기가 필요해보임

**Comment by awesomeo184** [comment]
![image](https://user-images.githubusercontent.com/63030569/196600051-ae9b79bc-dc0f-429b-b692-1ae64f67371e.png)

제출 내역 페이지

**Comment by awesomeo184** [comment]
![image](https://user-images.githubusercontent.com/63030569/196600227-999bc981-159d-4e0c-b246-7c6c7c6aa4ab.png)

제출자 이름 길이 제한이 없는 것 같습니다.
제출자 이름이 10자 이상이면, 처리를 막아놨기 때문에 제출되지 않습니다.

**Comment by jinyoungchoi95** [comment]
<img width="598" alt="스크린샷 2022-10-19 오후 2 26 34" src="https://user-images.githubusercontent.com/69106910/196604649-9338b94d-93ec-45c6-8fe1-60e60be54110.png">

이미지가 없으면 그냥 noimage 이미지조차 디스플레이 안하는게 좋아보임

**Comment by cks3066** [comment]
```
submission 상세 조회에서 왼쪽상단 홈을누르면 홈으로감 / 다른쪽에서는 아이콘 클릭에 대한 기능이없음

-> 왼쪽상단 아이콘버튼에 대한 동작 통일 필요해보임
```

```
웹 소켓 reconnect 관련 이슈
```

두 사항을 제외하고 전부 처리하였습니다.
